# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI React

on:
  pull_request:
    branches: [ master ]

jobs:
  Build-Teste:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - name: Pegando ultima vers찾o do c처digo      
      uses: actions/checkout@v2
      
    - name: Configurando Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Instalando dependencias 
      run: npm ci

      
    - name: Rodando o build
      run: npm run build --if-present

    - name: Rodando testes
      run: npm test
  
  Publicacao-DockerHub:
    needs: Build-Teste
    runs-on: ubuntu-latest

    steps:
      - name: Pegando ultima vers찾o do c처digo      
        uses: actions/checkout@v2 

      - name: Configurando Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x        

      - name: Instalando dependencias 
        run: npm ci
          
      - name: Rodando o build
        run: npm run build --if-present          